### ISSUE TITLE
Create a model solar system

### ISSUE THREAD

**Issue by bowseruk** [bowseruk/astraeus-travel#10]
Create a 2d model of the solar system

**Comment by Ing3rs** [comment]
@bowseruk  possible background images: 

- https://unsplash.com/photos/T26KCgCPsCI - it's high res so you could just use the top or bottom half
- https://unsplash.com/photos/L95xDkSSuWw
- https://unsplash.com/photos/-cKXtsJWU-I

**Comment by bowseruk** [comment]
Added the initial model.
